// packages/nova-ui/src/Skeleton/Skeleton.tsx
import { skeletonRecipe } from './Skeleton.css'

export interface SkeletonProps {
	variant?: 'text' | 'row'
	width?: string
	height?: string
	className?: string
}

/**
 * Skeleton placeholder with shimmer animation for loading states.
 */
export function Skeleton({ variant = 'text', width, height, className }: SkeletonProps) {
	const cls = skeletonRecipe({ variant })

	return (
		<div
			className={className ? `${cls} ${className}` : cls}
			style={{ width, height }}
			aria-hidden="true"
		/>
	)
}

// packages/nova-ui-svelte/src/lib/Skeleton/Skeleton.svelte
<script lang="ts">
	import { skeletonRecipe } from './Skeleton.css'

	interface Props {
		variant?: 'text' | 'row'
		width?: string
		height?: string
		class?: string
	}

	let { variant = 'text', width, height, class: className }: Props = $props()

	let cls = $derived(skeletonRecipe({ variant }))
</script>

<div
	class={className ? `${cls} ${className}` : cls}
	style:width={width}
	style:height={height}
	aria-hidden="true"
></div>
