// packages/nova-ui-solid/src/Alert/Alert.tsx
import type { JSX } from 'solid-js'
import { alertRecipe } from './Alert.css'

export interface AlertProps {
	variant: 'success' | 'error' | 'warning'
	children: JSX.Element
}

/**
 * Alert component for feedback messages with semantic variants.
 * Uses role="alert" for error/warning (assertive) and role="status" for success (polite).
 */
export function Alert(props: AlertProps): JSX.Element {
	return (
		<div
			class={alertRecipe({ variant: props.variant })}
			role={props.variant === 'success' ? 'status' : 'alert'}
		>
			{props.children}
		</div>
	)
}

// packages/nova-ui/src/Alert/Alert.tsx
import type { ReactNode } from 'react'
import { alertRecipe } from './Alert.css'

export interface AlertProps {
	variant: 'success' | 'error' | 'warning'
	children: ReactNode
	className?: string
}

/**
 * Alert component for feedback messages with semantic variants.
 * Uses role="alert" for error/warning (assertive) and role="status" for success (polite).
 */
export function Alert({ variant, children, className }: AlertProps) {
	const cls = alertRecipe({ variant })

	return (
		<div
			className={className ? `${cls} ${className}` : cls}
			role={variant === 'success' ? 'status' : 'alert'}
		>
			{children}
		</div>
	)
}
