// packages/nova-ui-svelte/src/lib/Alert/Alert.svelte
<script lang="ts">
	import { alertRecipe } from './Alert.css'

	interface Props {
		variant: 'success' | 'error' | 'warning'
		class?: string
		children?: any
	}

	let { variant, class: className, children }: Props = $props()

	let cls = $derived(alertRecipe({ variant }))
	let role = $derived(variant === 'success' ? 'status' : 'alert')
</script>

<div
	class={className ? `${cls} ${className}` : cls}
	{role}
>
	{@render children?.()}
</div>

// packages/nova-ui/src/Alert/Alert.tsx
import type { ReactNode } from 'react'
import { alertRecipe } from './Alert.css'

export interface AlertProps {
	variant: 'success' | 'error' | 'warning'
	children: ReactNode
	className?: string
}

/**
 * Alert component for feedback messages with semantic variants.
 * Uses role="alert" for error/warning (assertive) and role="status" for success (polite).
 */
export function Alert({ variant, children, className }: AlertProps) {
	const cls = alertRecipe({ variant })

	return (
		<div
			className={className ? `${cls} ${className}` : cls}
			role={variant === 'success' ? 'status' : 'alert'}
		>
			{children}
		</div>
	)
}
