// packages/nova-ui-solid/src/Skeleton/Skeleton.tsx
import { type JSX, splitProps } from 'solid-js'
import { skeletonRecipe } from './Skeleton.css'

export interface SkeletonProps extends JSX.HTMLAttributes<HTMLDivElement> {
	variant?: 'text' | 'row'
}

/**
 * Skeleton placeholder with shimmer animation.
 * Use variant="text" for inline text and variant="row" for table/list rows.
 */
export function Skeleton(props: SkeletonProps) {
	const [local, rest] = splitProps(props, ['variant', 'class'])

	const className = () => skeletonRecipe({ variant: local.variant })

	return (
		<div
			{...rest}
			class={local.class ? `${className()} ${local.class}` : className()}
			aria-hidden="true"
		/>
	)
}

// packages/nova-ui/src/Skeleton/Skeleton.tsx
import { skeletonRecipe } from './Skeleton.css'

export interface SkeletonProps {
	variant?: 'text' | 'row'
	width?: string
	height?: string
	className?: string
}

/**
 * Skeleton placeholder with shimmer animation for loading states.
 */
export function Skeleton({ variant = 'text', width, height, className }: SkeletonProps) {
	const cls = skeletonRecipe({ variant })

	return (
		<div
			className={className ? `${cls} ${className}` : cls}
			style={{ width, height }}
			aria-hidden="true"
		/>
	)
}
