// packages/nova-ui-svelte/src/lib/Input/Input.svelte
<script lang="ts">
	import * as styles from './Input.css'
	import type { HTMLInputAttributes } from 'svelte/elements'

	interface Props extends HTMLInputAttributes {
		label?: string
		error?: string
	}

	let {
		label,
		error,
		class: className,
		id,
		...rest
	}: Props = $props()

	let inputId = $derived(id ?? `input-${Math.random().toString(36).slice(2, 8)}`)
	let errorId = $derived(error ? `${inputId}-error` : undefined)
</script>

<div class={className ? `${styles.wrapper} ${className}` : styles.wrapper}>
	{#if label}
		<label class={styles.label} for={inputId}>{label}</label>
	{/if}
	<input
		{...rest}
		id={inputId}
		class={error ? `${styles.input} ${styles.inputError}` : styles.input}
		aria-invalid={error ? true : undefined}
		aria-describedby={errorId}
	/>
	{#if error}
		<span id={errorId} class={styles.errorMessage} role="alert">{error}</span>
	{/if}
</div>

// packages/nova-ui/src/Input/Input.tsx
import { type InputHTMLAttributes, forwardRef, useId } from 'react'
import * as styles from './Input.css'

export interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
	label?: string
	error?: string
}

export const Input = forwardRef<HTMLInputElement, InputProps>(
	({ label, error, id: propId, className, ...rest }, ref) => {
		const generatedId = useId()
		const id = propId ?? generatedId

		return (
			<div className={styles.wrapper}>
				{label && (
					<label className={styles.label} htmlFor={id}>
						{label}
					</label>
				)}
				<input
					ref={ref}
					id={id}
					className={`${styles.input}${error ? ` ${styles.inputError}` : ''}${className ? ` ${className}` : ''}`}
					aria-invalid={error ? true : undefined}
					aria-describedby={error ? `${id}-error` : undefined}
					{...rest}
				/>
				{error && (
					<span id={`${id}-error`} className={styles.errorMessage} role="alert">
						{error}
					</span>
				)}
			</div>
		)
	},
)

Input.displayName = 'Input'
