// packages/nova-ui-solid/src/Input/Input.tsx
import { type JSX, Show, createUniqueId, splitProps } from 'solid-js'
import * as styles from './Input.css'

export interface InputProps extends JSX.InputHTMLAttributes<HTMLInputElement> {
	label?: string
	error?: string
}

export function Input(props: InputProps) {
	const [local, inputAttrs] = splitProps(props, ['label', 'error', 'id', 'class'])
	const id = () => local.id ?? createUniqueId()

	return (
		<div class={styles.wrapper}>
			<Show when={local.label}>
				<label class={styles.label} for={id()}>
					{local.label}
				</label>
			</Show>
			<input
				id={id()}
				class={`${styles.input}${local.error ? ` ${styles.inputError}` : ''}${local.class ? ` ${local.class}` : ''}`}
				aria-invalid={local.error ? true : undefined}
				aria-describedby={local.error ? `${id()}-error` : undefined}
				{...inputAttrs}
			/>
			<Show when={local.error}>
				<span id={`${id()}-error`} class={styles.errorMessage} role="alert">
					{local.error}
				</span>
			</Show>
		</div>
	)
}

// packages/nova-ui/src/Input/Input.tsx
import { type InputHTMLAttributes, forwardRef, useId } from 'react'
import * as styles from './Input.css'

export interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
	label?: string
	error?: string
}

export const Input = forwardRef<HTMLInputElement, InputProps>(
	({ label, error, id: propId, className, ...rest }, ref) => {
		const generatedId = useId()
		const id = propId ?? generatedId

		return (
			<div className={styles.wrapper}>
				{label && (
					<label className={styles.label} htmlFor={id}>
						{label}
					</label>
				)}
				<input
					ref={ref}
					id={id}
					className={`${styles.input}${error ? ` ${styles.inputError}` : ''}${className ? ` ${className}` : ''}`}
					aria-invalid={error ? true : undefined}
					aria-describedby={error ? `${id}-error` : undefined}
					{...rest}
				/>
				{error && (
					<span id={`${id}-error`} className={styles.errorMessage} role="alert">
						{error}
					</span>
				)}
			</div>
		)
	},
)

Input.displayName = 'Input'
