// packages/nova-ui/src/StatusChip/StatusChip.tsx
import { statusChipRecipe } from './StatusChip.css'

export type RecordStatus = 'created' | 'accessed' | 'modified' | 'deleted'

export interface StatusChipProps {
	status: RecordStatus
	label?: string
	className?: string
}

/**
 * Displays a record status value as a colored pill chip.
 * Capitalizes the status value as default text if no label is provided.
 */
export function StatusChip({ status, label, className }: StatusChipProps) {
	const displayText = label ?? status.charAt(0).toUpperCase() + status.slice(1)
	const cls = statusChipRecipe({ status })

	return <span className={className ? `${cls} ${className}` : cls}>{displayText}</span>
}

// packages/nova-ui-svelte/src/lib/StatusChip/StatusChip.svelte
<script lang="ts">
	import { statusChipRecipe } from './StatusChip.css'

	type RecordStatus = 'created' | 'accessed' | 'modified' | 'deleted'

	interface Props {
		status: RecordStatus
		label?: string
		class?: string
	}

	let { status, label, class: className }: Props = $props()

	let cls = $derived(statusChipRecipe({ status }))
	let displayText = $derived(label ?? status.charAt(0).toUpperCase() + status.slice(1))
</script>

<span class={className ? `${cls} ${className}` : cls}>
	{displayText}
</span>
