// packages/nova-ui-svelte/src/lib/Card/Card.svelte
<script lang="ts">
	import * as styles from './Card.css'
	import type { HTMLAttributes } from 'svelte/elements'

	interface Props extends HTMLAttributes<HTMLDivElement> {
		title?: string
	}

	let { title, class: className, children, ...rest }: Props = $props()
</script>

<div class={className ? `${styles.card} ${className}` : styles.card} {...rest}>
	{#if title}
		<h3 class={styles.cardTitle}>{title}</h3>
	{/if}
	{@render children?.()}
</div>

// packages/nova-ui/src/Card/Card.tsx
import { type HTMLAttributes, type ReactNode, forwardRef } from 'react'
import { card, cardTitle } from './Card.css'

export interface CardProps extends HTMLAttributes<HTMLDivElement> {
	title?: string
	children: ReactNode
}

export const Card = forwardRef<HTMLDivElement, CardProps>(
	({ title, children, className, ...rest }, ref) => {
		return (
			<div ref={ref} className={className ? `${card} ${className}` : card} {...rest}>
				{title && <h3 className={cardTitle}>{title}</h3>}
				{children}
			</div>
		)
	},
)

Card.displayName = 'Card'
