// packages/nova-ui-solid/src/Card/Card.tsx
import { type JSX, splitProps } from 'solid-js'
import { card, cardTitle } from './Card.css'

export interface CardProps extends JSX.HTMLAttributes<HTMLDivElement> {
	title?: string
}

/**
 * Simple container card with optional title.
 */
export function Card(props: CardProps) {
	const [local, rest] = splitProps(props, ['title', 'children', 'class'])

	return (
		<div {...rest} class={local.class ? `${card} ${local.class}` : card}>
			{local.title && <h3 class={cardTitle}>{local.title}</h3>}
			{local.children}
		</div>
	)
}

// packages/nova-ui/src/Card/Card.tsx
import { type HTMLAttributes, type ReactNode, forwardRef } from 'react'
import { card, cardTitle } from './Card.css'

export interface CardProps extends HTMLAttributes<HTMLDivElement> {
	title?: string
	children: ReactNode
}

export const Card = forwardRef<HTMLDivElement, CardProps>(
	({ title, children, className, ...rest }, ref) => {
		return (
			<div ref={ref} className={className ? `${card} ${className}` : card} {...rest}>
				{title && <h3 className={cardTitle}>{title}</h3>}
				{children}
			</div>
		)
	},
)

Card.displayName = 'Card'
